### ISSUE TITLE
gcn3d : getting nan value 

### ISSUE THREAD

**Issue by charvi-077** [j1a0m0e4sNTU/3dgcn#12]
Hi, 

Thanks for providing the code. I was trying to setting up this repository with my another dataset where a single point cloud has 30k points. But in forward pass in first layer itself ( gcn3d.Conv_surface) the data value are getting nan at some positions , and resulting in loss as nan. So I wonder where I am going wrong  ? 

Looking forward to reply. 

Thanks, 
Charvi

**Comment by chih-hao-lin** [comment]
thanks for your interest in our code! Getting nan values usually comes from operations (normalization, division) involving zero values, I guess there're some points with same position in the point cloud that cause the [normalization](https://github.com/zhihao-lin/3dgcn/blob/c9a540693f84ae9cae01c82c12baee6073c9940b/gcn3d.py#L52C31-L52C42) generate nan. You could try to double check and add some small value ($10^{-5}$) before this operation. 
Hope this helps.
