### ISSUE TITLE
Performance analysis

### ISSUE THREAD

**Issue by pvnieo** [j1a0m0e4sNTU/3dgcn#3]
Hi, 

Thank you for the good paper, and for sharing the code.

I'd like to know if you have done a performance analysis in term of execution time. For example, how much does it take to train the classification or the segmentation method, or how mush does it take to do one iteration over the data?

Thank you in advance!

**Comment by chih-hao-lin** [comment]
Hi,
For each model file, I provide unit test function, and you can evaluate inference time for a single batch.
As for the training time, in my experience, it took about 8 hours for the classification task and about 1 day for the segmentation task.

**Comment by pvnieo** [comment]
Hi,
This answer the question. Thank you for your response.
closing the issue!
