### ISSUE TITLE
Degradation of results when rotation

### ISSUE THREAD

**Issue by pvnieo** [j1a0m0e4sNTU/3dgcn#4]
Hi,

Thank you for the great publication.

In fact, I'm a bit surprised that the results degrade if you rotate the objects, because rotation is a rigid transformation like the shift. If you rotate, the neighbor of the points doesn't change, as well as the distance between them, so how can you explain this degradation?

Thank you in advance for your answer!

**Comment by chih-hao-lin** [comment]
Rotation doesn't affect the relative distance but changes the direction vectors, which are used for 3d graph convolution. 
While the performance degrades, our model is more robust under shape rotation, compared to previous works.

**Comment by pvnieo** [comment]
This answer the question. Thank you.
closing the issue!
