### ISSUE TITLE
Visualization Issues

### ISSUE THREAD

**Issue by qsisi** [j1a0m0e4sNTU/3dgcn#9]
Hello!

Thanks for open-sourcing this amazing work! Now I have a question about the figures in the paper.

Could you tell me how to get the visualization results in **Figure-5** of the paper? Specifically, how to draw the transparent sphere with a discrete point cloud inside the sphere? Which tool did you use to render the point clouds to get that visualization results?

Thank you so much for your help!

**Comment by peterjohnsonhuang** [comment]
I believe that it was drawn using PowerPoint. As for the point cloud， the visualization was done the same way as our segmentation results. Just saving an airplane image with all the points set to orange and manually pasting it onto a sphere object will do the work. I hope this answers your question.

**Comment by qsisi** [comment]
Thanks for your answer.
